### ISSUE TITLE
404 au lancement de padpo vide

### ISSUE THREAD

**Issue by Seluj78** [vpoulailleau/padpo#7]
```
(python-docs-i18n) ➜  python-docs-fr git:(3.8) pip install --upgrade pip padpo potodo pospell powrap
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already up-to-date: pip in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (19.3.1)
Collecting padpo
  Downloading https://files.pythonhosted.org/packages/cc/78/34e0096714a5412acccb78c92fff709dbd1c599f901596a000da15c7edee/padpo-0.3.0-py3-none-any.whl
Requirement already up-to-date: potodo in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (0.0.9)
Requirement already up-to-date: pospell in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (1.0.3)
Requirement already up-to-date: powrap in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (0.3.0)
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Collecting simplelogging
  Using cached https://files.pythonhosted.org/packages/63/00/e173efe1df19b62a599b2c543245fc01976ce7cdc2c32f6d16c1288b8fd6/simplelogging-0.10.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from padpo) (2.21.0)
Requirement already satisfied, skipping upgrade: polib in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from potodo) (1.1.0)
Requirement already satisfied, skipping upgrade: regex in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from pospell) (2019.8.19)
Requirement already satisfied, skipping upgrade: docutils>=0.11 in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from pospell) (0.14)
Requirement already satisfied, skipping upgrade: tqdm in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from powrap) (4.36.1)
Collecting colorlog==4.0.2
  Using cached https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from requests->padpo) (2018.11.29)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from requests->padpo) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from requests->padpo) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages (from requests->padpo) (2.8)
Installing collected packages: wheel, colorlog, simplelogging, padpo
Successfully installed colorlog-4.0.2 padpo-0.3.0 simplelogging-0.10.0 wheel-0.33.6
(python-docs-i18n) ➜  python-docs-fr git:(3.8) padpo
Traceback (most recent call last):
  File "/Users/seluj78/.venvs/python-docs-i18n/bin/padpo", line 8, in <module>
    sys.exit(main())
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/padpo/padpo.py", line 522, in main
    path, pull_request_info = pull_request_files(pull_request)
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/padpo/padpo.py", line 458, in pull_request_files
    request.raise_for_status()
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos//files
(python-docs-i18n) ➜  python-docs-fr git:(3.8)
```

**Comment by Seluj78** [comment]
En revanche quand j'ai lancé `padpo -p 920` juste apres aucun problème

**Comment by vpoulailleau** [comment]
Effectivement, c'est pas normal d'appeler padpo tout court, on est censé lui dire quoi checker. J'ai rendu ça obligatoire dans la ligne de commande :

```
$ padpo
usage: padpo [-h] [-v] (-i PATH | -g python/python-docs-fr/pull/978 | -p 978)
padpo: error: one of the arguments -i/--input-path -g/--github -p/--python-docs-fr is required
```

**Comment by Seluj78** [comment]
Whooot whooot
